# Generated by Django 3.2.5 on 2021-07-30 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cars_car_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
