# Generated by Django 3.2.5 on 2021-08-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210731_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
