# Generated by Django 3.2.5 on 2021-08-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_booking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
