# Generated by Django 3.2.5 on 2021-08-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_booking_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
