# Generated by Django 3.2.5 on 2021-08-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_cars_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
